repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: trailing-whitespace
    rev: 'v2.3.0'
  - repo: https://github.com/psf/black
    hooks:
      - id: black
    rev: '21.12b0'
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    hooks:
      - id: pylint
    rev: "v2.12.2"